all: martlet9.urdf landingpad.urdf

martlet9.urdf: martlet9.urdf.xacro
	xacro -i martlet9.urdf.xacro > martlet9.urdf

landingpad.urdf: landingpad.urdf.xacro
	xacro -i landingpad.urdf.xacro > landingpad.urdf
